export const regionList = ["Europe", "Africa", "Americas", "Asia", "Oceania"];

export const countryList = [
    "South Africa",
    "DR Congo",
    "South Sudan",
    "Zambia",
    "São Tomé and Príncipe",
    "Mayotte",
    "Uganda",
    "Mali",
    "Namibia",
    "Réunion",
    "Madagascar",
    "Chad",
    "Western Sahara",
    "Burkina Faso",
    "Djibouti",
    "Algeria",
    "Sierra Leone",
    "Mauritius",
    "Zimbabwe",
    "Rwanda",
    "Gambia",
    "Mauritania",
    "Morocco",
    "Liberia",
    "Somalia",
    "Saint Helena, Ascension and Tristan da Cunha",
    "Benin",
    "Malawi",
    "Ghana",
    "Eswatini",
    "Guinea-Bissau",
    "Botswana",
    "Libya",
    "Senegal",
    "Guinea",
    "Burundi",
    "British Indian Ocean Territory",
    "Republic of the Congo",
    "Kenya",
    "Tunisia",
    "Central African Republic",
    "Nigeria",
    "Sudan",
    "Seychelles",
    "Tanzania",
    "Ivory Coast",
    "Eritrea",
    "Ethiopia",
    "Comoros",
    "Togo",
    "Cape Verde",
    "Lesotho",
    "Angola",
    "Equatorial Guinea",
    "Mozambique",
    "Gabon",
    "Niger",
    "Cameroon",
    "Egypt",
    "Dominican Republic",
    "Guatemala",
    "Chile",
    "Uruguay",
    "Turks and Caicos Islands",
    "Saint Lucia",
    "El Salvador",
    "Cuba",
    "Trinidad and Tobago",
    "Saint Martin",
    "Antigua and Barbuda",
    "Grenada",
    "United States Minor Outlying Islands",
    "French Guiana",
    "Peru",
    "Saint Pierre and Miquelon",
    "Dominica",
    "Suriname",
    "Costa Rica",
    "Martinique",
    "Nicaragua",
    "Honduras",
    "Guyana",
    "Paraguay",
    "Sint Maarten",
    "Jamaica",
    "Venezuela",
    "Aruba",
    "British Virgin Islands",
    "Caribbean Netherlands",
    "Cayman Islands",
    "Bahamas",
    "Puerto Rico",
    "Ecuador",
    "United States",
    "USA",
    "Mexico",
    "Saint Vincent and the Grenadines",
    "Curaçao",
    "Bolivia",
    "Barbados",
    "Belize",
    "Guadeloupe",
    "Saint Barthélemy",
    "Argentina",
    "Haiti",
    "Brazil",
    "Colombia",
    "Montserrat",
    "United States Virgin Islands",
    "Saint Kitts and Nevis",
    "Anguilla",
    "Bermuda",
    "Canada",
    "Falkland Islands",
    "Panama",
    "Greenland",
    "Nepal",
    "Laos",
    "Syria",
    "Singapore",
    "Azerbaijan",
    "Brunei",
    "Kyrgyzstan",
    "Cambodia",
    "Iraq",
    "Georgia",
    "Yemen",
    "South Korea",
    "Bhutan",
    "China",
    "Vietnam",
    "Oman",
    "Sri Lanka",
    "Bangladesh",
    "Afghanistan",
    "Taiwan",
    "Qatar",
    "Thailand",
    "Turkey",
    "Kuwait",
    "Tajikistan",
    "United Arab Emirates",
    "India",
    "Pakistan",
    "Jordan",
    "Lebanon",
    "Malaysia",
    "Saudi Arabia",
    "Timor-Leste",
    "Uzbekistan",
    "Israel",
    "North Korea",
    "Philippines",
    "Kazakhstan",
    "Hong Kong",
    "Palestine",
    "Turkmenistan",
    "Myanmar",
    "Iran",
    "Macau",
    "Japan",
    "Mongolia",
    "Bahrain",
    "Indonesia",
    "Armenia",
    "Maldives",
    "Malta",
    "Andorra",
    "Finland",
    "San Marino",
    "Italy",
    "Portugal",
    "Austria",
    "Luxembourg",
    "Albania",
    "Ukraine",
    "France",
    "Serbia",
    "North Macedonia",
    "Spain",
    "Ireland",
    "Slovakia",
    "Svalbard and Jan Mayen",
    "Hungary",
    "Montenegro",
    "United Kingdom",
    //"Scotland",
    //"Wales",
    //"Northern Ireland",
    "Iceland",
    "Estonia",
    "Slovenia",
    "Monaco",
    "Latvia",
    "Sweden",
    "Netherlands",
    "Belarus",
    "Gibraltar",
    "Guernsey",
    "Liechtenstein",
    "Croatia",
    "Switzerland",
    "Czechia",
    "Åland Islands",
    "Isle of Man",
    "Bosnia and Herzegovina",
    "Kosovo",
    "Lithuania",
    "Bulgaria",
    "Greece",
    "Jersey",
    "Faroe Islands",
    "Romania",
    "Moldova",
    "Denmark",
    "Norway",
    "Poland",
    "Germany",
    "Belgium",
    "Cyprus",
    "Vatican City",
    "Russia",
    "Solomon Islands",
    "Samoa",
    "New Zealand",
    "New Caledonia",
    "Tonga",
    "Tokelau",
    "Niue",
    "Australia",
    "Papua New Guinea",
    "Christmas Island",
    "Wallis and Futuna",
    "French Polynesia",
    "Fiji",
    "Nauru",
    "Pitcairn Islands",
    "Palau",
    "Micronesia",
    "Northern Mariana Islands",
    "Norfolk Island",
    "Kiribati",
    "Vanuatu",
    "Marshall Islands",
    "American Samoa",
    "Cocos (Keeling) Islands",
    "Tuvalu",
    "Guam",
    "Cook Islands",
];

/*export const countryList = [
    "south africa",
    "dr congo",
    "south sudan",
    "zambia",
    "são tomé and príncipe",
    "mayotte",
    "uganda",
    "mali",
    "namibia",
    "réunion",
    "madagascar",
    "chad",
    "western sahara",
    "burkina faso",
    "djibouti",
    "algeria",
    "sierra leone",
    "mauritius",
    "zimbabwe",
    "rwanda",
    "gambia",
    "mauritania",
    "morocco",
    "liberia",
    "somalia",
    "saint helena, ascension and tristan da cunha",
    "benin",
    "malawi",
    "ghana",
    "eswatini",
    "guinea-bissau",
    "botswana",
    "libya",
    "senegal",
    "guinea",
    "burundi",
    "british indian ocean territory",
    "republic of the congo",
    "kenya",
    "tunisia",
    "central african republic",
    "nigeria",
    "sudan",
    "seychelles",
    "tanzania",
    "ivory coast",
    "eritrea",
    "ethiopia",
    "comoros",
    "togo",
    "cape verde",
    "lesotho",
    "angola",
    "equatorial guinea",
    "mozambique",
    "gabon",
    "niger",
    "cameroon",
    "egypt",
    "dominican republic",
    "guatemala",
    "chile",
    "uruguay",
    "turks and caicos islands",
    "saint lucia",
    "el salvador",
    "cuba",
    "trinidad and tobago",
    "saint martin",
    "antigua and barbuda",
    "grenada",
    "united states minor outlying islands",
    "french guiana",
    "peru",
    "saint pierre and miquelon",
    "dominica",
    "suriname",
    "costa rica",
    "martinique",
    "nicaragua",
    "honduras",
    "guyana",
    "paraguay",
    "sint maarten",
    "jamaica",
    "venezuela",
    "aruba",
    "british virgin islands",
    "caribbean netherlands",
    "cayman islands",
    "bahamas",
    "puerto rico",
    "ecuador",
    "united states",
    "usa",
    "us",
    "mexico",
    "saint vincent and the grenadines",
    "curaçao",
    "bolivia",
    "barbados",
    "belize",
    "guadeloupe",
    "saint barthélemy",
    "argentina",
    "haiti",
    "brazil",
    "colombia",
    "montserrat",
    "united states virgin islands",
    "saint kitts and nevis",
    "anguilla",
    "bermuda",
    "canada",
    "falkland islands",
    "panama",
    "greenland",
    "nepal",
    "laos",
    "syria",
    "singapore",
    "azerbaijan",
    "brunei",
    "kyrgyzstan",
    "cambodia",
    "iraq",
    "georgia",
    "yemen",
    "south korea",
    "bhutan",
    "china",
    "vietnam",
    "oman",
    "sri lanka",
    "bangladesh",
    "afghanistan",
    "taiwan",
    "qatar",
    "thailand",
    "turkey",
    "kuwait",
    "tajikistan",
    "united arab emirates",
    "india",
    "pakistan",
    "jordan",
    "lebanon",
    "malaysia",
    "saudi arabia",
    "timor-leste",
    "uzbekistan",
    "israel",
    "north korea",
    "philippines",
    "kazakhstan",
    "hong kong",
    "palestine",
    "turkmenistan",
    "myanmar",
    "iran",
    "macau",
    "japan",
    "mongolia",
    "bahrain",
    "indonesia",
    "armenia",
    "maldives",
    "malta",
    "andorra",
    "finland",
    "san marino",
    "italy",
    "portugal",
    "austria",
    "luxembourg",
    "albania",
    "ukraine",
    "france",
    "serbia",
    "north macedonia",
    "spain",
    "ireland",
    "slovakia",
    "svalbard and jan mayen",
    "hungary",
    "montenegro",
    "united kingdom",
    "uk",
    "england",
    "scotland",
    "wales",
    "northern ireland",
    "iceland",
    "estonia",
    "slovenia",
    "monaco",
    "latvia",
    "sweden",
    "netherlands",
    "belarus",
    "gibraltar",
    "guernsey",
    "liechtenstein",
    "croatia",
    "switzerland",
    "czechia",
    "åland islands",
    "isle of man",
    "bosnia and herzegovina",
    "kosovo",
    "lithuania",
    "bulgaria",
    "greece",
    "jersey",
    "faroe islands",
    "romania",
    "moldova",
    "denmark",
    "norway",
    "poland",
    "germany",
    "belgium",
    "cyprus",
    "vatican city",
    "russia",
    "solomon islands",
    "samoa",
    "new zealand",
    "new caledonia",
    "tonga",
    "tokelau",
    "niue",
    "australia",
    "papua new guinea",
    "christmas island",
    "wallis and futuna",
    "french polynesia",
    "fiji",
    "nauru",
    "pitcairn islands",
    "palau",
    "micronesia",
    "northern mariana islands",
    "norfolk island",
    "kiribati",
    "vanuatu",
    "marshall islands",
    "american samoa",
    "cocos (keeling) islands",
    "tuvalu",
    "guam",
    "cook islands",
];*/
